apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poller
  name: poller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poller
    spec:
      containers:
      - image: registry.gitlab.com/tikal-external/academy-public/images/poller
        name: poller
        resources: {}
status: {}
