apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
 - ns.yaml
 - ./api/deployment.yaml
 - ./api/svc.yaml
 - ./pinger/deployment.yaml
 - ./poller/deployment.yaml
 - ./redis/deployment.yaml
 - ./redis/svc.yaml

namespace: everc