apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pinger
  name: pinger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pinger
    spec:
      containers:
      - image: registry.gitlab.com/tikal-external/academy-public/images/pinger:latest
        name: pinger
        resources: {}
status: {}
